kind: List
apiVersion: v1
items:
  - kind: ImageStream
    apiVersion: image.openshift.io/v1
    metadata:
      labels:
        app: cyborg-regidores
        component: webhook2kafka
      name: webhook2kafka
    spec:
      lookupPolicy:
        local: true
  - kind: ImageStream
    apiVersion: image.openshift.io/v1
    metadata:
      labels:
        app: cyborg-regidores
        component: normalizers
      name: normalizers
    spec:
      lookupPolicy:
        local: true
